### ISSUE TITLE
Issues Building NOOBS On Ubuntu 18.10

### ISSUE THREAD

**Issue by flash76** [raspberrypi/noobs#522]
Hi, I tried building NOOBS. I installed all of the dependencies and ran `BUILDME.sh`. It starts off okay and then errors out. Here are the messages:
`freadahead.c: In function 'freadahead':
freadahead.c:91:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
   ^~~~~
make[4]: *** [Makefile:1842: freadahead.o] Error 1
make[4]: *** Waiting for unfinished jobs....
fseeko.c: In function 'rpl_fseeko':
fseeko.c:109:4: error: #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
   #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
    ^~~~~
make[4]: *** [Makefile:1842: fseeko.o] Error 1
make[4]: Leaving directory '/home/varun/Documents/GitHub/noobs/buildroot/output/build/host-m4-1.4.17/lib'
make[3]: *** [Makefile:1602: all] Error 2
make[3]: Leaving directory '/home/varun/Documents/GitHub/noobs/buildroot/output/build/host-m4-1.4.17/lib'
make[2]: *** [Makefile:1506: all-recursive] Error 1
make[2]: Leaving directory '/home/varun/Documents/GitHub/noobs/buildroot/output/build/host-m4-1.4.17'
make[1]: *** [Makefile:1461: all] Error 2
make[1]: Leaving directory '/home/varun/Documents/GitHub/noobs/buildroot/output/build/host-m4-1.4.17'
make: *** [package/pkg-generic.mk:185: /home/varun/Documents/GitHub/noobs/buildroot/output/build/host-m4-1.4.17/.stamp_built] Error 2`
I think this is where the error is. Previously, I tried deleting the lines in the `freadahead.c` and `fseeko.c` files that were causing the errors. That caused more problems.

**Comment by Fatflo** [comment]
same issue on ubuntu 19.04

**Comment by procount** [comment]
You'll need to go back to Ubuntu14.04 for it to work. Not sure about 16.04 because I've not tried it.

There are many patches required to get it to build on 18.04, but maybe you could port them from PINN?

**Comment by RaspberryPiFan** [comment]
> You'll need to go back to Ubuntu14.04 for it to work. Not sure about 16.04 because I've not tried it.
> 
> There are many patches required to get it to build on 18.04, but maybe you could port them from PINN?

I'm fixing PINN's building right now, then I made a copy of this for NOOBS.

**Comment by RaspberryPiFan** [comment]
Making progress with PINN fixes, but it takes some time since I also have to port PINN/NOOBS to QT5
